game_data = [
    {"name": "Cristiano Ronaldo", "followers": 630_000_000, "description": "Footballer", "country": "Portugal"},
    {"name": "Ariana Grande", "followers": 380_000_000, "description": "Singer and actress", "country": "United States"},
    {"name": "Dwayne Johnson", "followers": 390_000_000, "description": "Actor and former wrestler", "country": "United States"},
    {"name": "Kylie Jenner", "followers": 400_000_000, "description": "Model and entrepreneur", "country": "United States"},
    {"name": "Lionel Messi", "followers": 510_000_000, "description": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "followers": 430_000_000, "description": "Singer and actress", "country": "United States"},
    {"name": "Kim Kardashian", "followers": 360_000_000, "description": "Media personality and businesswoman", "country": "United States"},
    {"name": "Virat Kohli", "followers": 270_000_000, "description": "Cricketer", "country": "India"},
    {"name": "Neymar Jr", "followers": 220_000_000, "description": "Footballer", "country": "Brazil"},
    {"name": "Taylor Swift", "followers": 290_000_000, "description": "Singer-songwriter", "country": "United States"},
    {"name": "Zendaya", "followers": 180_000_000, "description": "Actress and singer", "country": "United States"},
    {"name": "Billie Eilish", "followers": 150_000_000, "description": "Singer-songwriter", "country": "United States"},
    {"name": "Shakira", "followers": 160_000_000, "description": "Singer and dancer", "country": "Colombia"},
    {"name": "Robert Downey Jr.", "followers": 100_000_000, "description": "Actor", "country": "United States"},
    {"name": "David Beckham", "followers": 80_000_000, "description": "Former footballer", "country": "United Kingdom"},
    {"name": "LeBron James", "followers": 160_000_000, "description": "Basketball player", "country": "United States"},
    {"name": "Emma Watson", "followers": 75_000_000, "description": "Actress and activist", "country": "United Kingdom"},
    {"name": "Shawn Mendes", "followers": 70_000_000, "description": "Singer-songwriter", "country": "Canada"},
    {"name": "Gigi Hadid", "followers": 78_000_000, "description": "Model", "country": "United States"},
    {"name": "Chris Hemsworth", "followers": 100_000_000, "description": "Actor", "country": "Australia"},
    {"name": "Blackpink", "followers": 95_000_000, "description": "K-pop group", "country": "South Korea"},
    {"name": "BTS", "followers": 90_000_000, "description": "K-pop group", "country": "South Korea"},
    {"name": "Will Smith", "followers": 70_000_000, "description": "Actor and rapper", "country": "United States"},
    {"name": "Rihanna", "followers": 155_000_000, "description": "Singer and entrepreneur", "country": "Barbados"},
    {"name": "Drake", "followers": 130_000_000, "description": "Rapper and songwriter", "country": "Canada"},
    {"name": "Kendall Jenner", "followers": 290_000_000, "description": "Model and TV personality", "country": "United States"},
    {"name": "Zlatan Ibrahimović", "followers": 60_000_000, "description": "Footballer", "country": "Sweden"},
    {"name": "Gal Gadot", "followers": 95_000_000, "description": "Actress and model", "country": "Israel"},
    {"name": "Ed Sheeran", "followers": 95_000_000, "description": "Singer-songwriter", "country": "United Kingdom"},
    {"name": "Millie Bobby Brown", "followers": 70_000_000, "description": "Actress", "country": "United Kingdom"}
]
